from setuptools import setup, find_packages


setup(name='asm.cms',
      version='0.1dev',
      description="Assembly Website CMS",
      author="Webcrew",
      author_email="web@assembly.org",
      url="",
      license="proprietary",
      packages=find_packages('src'),
      package_dir={'': 'src'},
      include_package_data=True,
      zip_safe=False,
      install_requires=['setuptools',
                        'grok',
                        'grokui.admin',

                        'ZODB3',
                        'megrok.pagelet',
                        'zc.resourcelibrary',
                        'zc.sourcefactory',
                        'zope.app.container',
                        'zope.app.form',
                        'zope.app.generations',
                        'zope.deferredimport',
                        'zope.event',
                        'zope.html',
                        'zope.interface',
                        'zope.lifecycleevent',
                        'zope.schema',
                        'zope.traversing',
                        ],
      )
